# Dependabot configuration for GitHub-native dependency updates
# This works alongside Renovate to provide redundant dependency tracking
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    reviewers:
      - "HeartlessVeteran2"
    
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"  
      time: "07:00"
    reviewers:
      - "HeartlessVeteran2"
    # Ignore indirect dependencies to reduce noise
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
        
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"
      day: "thursday"
      time: "08:00" 
    reviewers:
      - "HeartlessVeteran2"